version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.0
jobs:
  test:
    docker:
      - image: cypress/base:10
        environment:
          TERM: xterm
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "package.json" }}
            - v3-dependencies-

      - run: |
          npm install

      - save_cache:
          paths:
            - node_modules
            - ~/.cache
          key: v3-dependencies-{{ checksum "package.json" }}

      - run: |
          npm run test

      - store_test_results:
          path: test-results
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots

      - run: |
          npm run build

      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  deploy-staging:
    docker:
      - image: circleci/python:2.7-jessie
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy to s3
          command: |
            cd dist
            aws s3 sync . s3://$S3_BUCKET/$S3_PATH

workflows:
  version: 2.1
  build-deploy:
    jobs:
      - test
      - deploy-staging:
          requires:
            - test
          filters:
            branches:
              only: release
